name: sync_pad
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  intl: ^0.20.2
  uuid: ^4.5.1
  meta: ^1.16.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  get_it: ^8.0.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
